name: CI/CD Pipeline for Task4

on:
  push:
    paths:
      - 'Task4/**'
  pull_request:
    paths:
      - 'Task4/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (v18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Change directory to Task4 and install dependencies
      - name: Install dependencies in Task4
        run: |
          cd Task4
          npm install

      # Step 4: Build the Task4 project
      - name: Build Task4 project
        run: |
          cd Task4
          npm run build

      # Step 5: Set up Docker Buildx for Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Login to Docker Hub (optional)
      # Ensure you add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as repository secrets in GitHub.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build the Docker image from Task4
      - name: Build Docker image for Task4
        run: |
          cd Task4
          docker build -t yourdockerhubusername/task4:latest .

      # Step 8: Push the Docker image (optional)
      - name: Push Docker image for Task4
        run: |
          cd Task4
          docker push yourdockerhubusername/task4:latest
